### ISSUE TITLE
Instant crouch to Stand

### ISSUE THREAD

**Issue by obscure021** [lukeskt/InputSystemFirstPersonCharacter#1]
I don't know if anyone has noticed but changing only controller height for crouching isn't a viable option. 
The center of the controller should be changed for a smoothened crouch.
I searched on youtube and came along with this, you can watch that video at this link:
[https://www.youtube.com/watch?v=Ksy42wRaaA4](https://www.youtube.com/watch?v=Ksy42wRaaA4)

**Comment by lukeskt** [comment]
Hi there,

As per the readme I threw this together really quickly, so the implementation details aren't that great. Crouch is indeed very rough. If you want to make improvements to the crouch and submit a pull request I'd be happy to review it and add it.

Thanks,

Luke

**Comment by lukeskt** [comment]
Pull request was beyond scope of this request, rewriting all code in repo. Please feel free to use your own controller implementation in your own repo. A simple improved crouch integrated into existing code would have been preferred. I may revisit crouch when I have time and implement it in a way sympathetic to the existing code and ethos of this repo, based in single file implementation with a focus on simplicity, hackability, and as a learning resource for others struggling with input system controllers. For now I'll close this.

**Comment by obscure021** [comment]
If that's the point, this line should work for a smooth crouch:
`controller.center = new Vector3(0, controller.height/2, 0)`
I **haven't tested** it but it should work just fine.
Goodbye.
